name: "Publish python poetry package"
author: "@JRubics"
description: "An action to build and publish python package to https://pypi.org/ using poetry https://github.com/sdispater/poetry"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  python_version:
    description: "The version of python to install"
    required: false
    default: "latest"
  poetry_version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
  pypi_token:
    description: "API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/) or TestPyPI (https://test.pypi.org/manage/account/)"
    required: false
  repository_name:
    description: "Name of a repository where the package will be uploaded"
    required: false
  repository_url:
    description: "URL where the package will be uploaded"
    required: false
  repository_username:
    description: "Username to log in into a repository where the package will be uploaded if using http-basic authentification instead of api token"
    required: false
  repository_password:
    description: "Password to log in into a repository where the package will be uploaded if using http-basic authentification instead of api token"
    required: false
  build_format:
    description: 'The build format to be used, either "sdist" or "wheel"'
    required: false
  ignore_dev_requirements:
    description: "Install project without developer requirements."
    required: false
  allow_poetry_pre_release:
    description: "Allow usage of poetry pre-release and development versions"
    required: false
  extra_build_dependency_packages:
    description: "An optional space-separated list of debian packages to be installed before building the package"
    required: false
  plugins:
    description: "An optional space-separated list of poetry plugins to be installed before building the package"
    required: false
runs:
  using: "docker"
  image: "docker://jrubics/poetry-publish:v1.10"
  args:
    - ${{ inputs.python_version }}
    - ${{ inputs.poetry_version }}
    - ${{ inputs.pypi_token }}
    - ${{ inputs.repository_name}}
    - ${{ inputs.repository_url }}
    - ${{ inputs.build_format }}
    - ${{ inputs.ignore_dev_requirements }}
    - ${{ inputs.allow_poetry_pre_release }}
    - ${{ inputs.repository_username }}
    - ${{ inputs.repository_password }}
    - ${{ inputs.extra_build_dependency_packages }}
    - ${{ inputs.plugins }}
