name: "Publish python poetry package"
author: "@JRubics"
description: "An action to build and publish python package to https://pypi.org/ using poetry https://github.com/sdispater/poetry"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  python_version:
    description: "The version of python to install"
    required: false
    default: "latest"
  poetry_version:
    description: "The version of poetry to install"
    required: false
    default: "latest"
  pypi_token:
    description: "API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/) or TestPyPI (https://test.pypi.org/manage/account/)"
    required: false
  repository_name:
    description: "Name of a repository where the package will be uploaded"
    required: false
  repository_url:
    description: "URL where the package will be uploaded"
    required: false
  repository_username:
    description: "Username to log in into a repository where the package will be uploaded if using http-basic authentification instead of api token"
    required: false
  repository_password:
    description: "Password to log in into a repository where the package will be uploaded if using http-basic authentification instead of api token"
    required: false
  build_format:
    description: 'The build format to be used, either "sdist" or "wheel"'
    required: false
  poetry_install_options:
    description: 'Adds possibility to pass options to "poetry install" command'
    required: false
  allow_poetry_pre_release:
    description: "Allow usage of poetry pre-release and development versions"
    required: false
  extra_build_dependency_packages:
    description: "An optional space-separated list of debian packages to be installed before building the package"
    required: false
  plugins:
    description: "An optional space-separated list of poetry plugins to be installed before building the package"
    required: false
  package_directory:
    description: "An optional subdirectory path if poetry package doesn't reside in the main workflow directory"
    required: false
    default: "."
  poetry_publish_options:
    description: 'Adds possibility to pass options to "poetry publish" command'
    required: false
runs:
  using: "docker"
  image: "docker://jrubics/poetry-publish:v2.0"
  args:
    - ${{ inputs.python_version }}
    - ${{ inputs.poetry_version }}
    - ${{ inputs.pypi_token }}
    - ${{ inputs.repository_name}}
    - ${{ inputs.repository_url }}
    - ${{ inputs.build_format }}
    - ${{ inputs.poetry_install_options }}
    - ${{ inputs.allow_poetry_pre_release }}
    - ${{ inputs.repository_username }}
    - ${{ inputs.repository_password }}
    - ${{ inputs.extra_build_dependency_packages }}
    - ${{ inputs.plugins }}
    - ${{ inputs.package_directory }}
    - ${{ inputs.poetry_publish_options }}
